blank_issues_enabled: false
contact_links:
  - name: mts Discord discussion
    url: https://discord.gg/mts-oss
    about: Please ask and answer questions here.
  - name: Report a security vulnerability
    url: https://github.com/block/mts/security/policy
    about: Please report security vulnerabilities here.
